# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: githubCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Test Start
      run: xcodebuild clean test -project EssentialFeed.xcodeproj -scheme CI -destination 'platform=macOS, arch=x86_64, id=4203018E-580F-C1B5-9525-B745CECA79EB'CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
